### ISSUE TITLE
Help understanding asyncore-based transport

### ISSUE THREAD

**Issue by EvoBloody** [etingof/pysnmp#108]
Hi!
I'm a new user of SNMP. And what I need is a snmp_trap listener. I read the document and find [this example](https://github.com/etingof/pysnmp/blob/master/examples/v1arch/asyncore/manager/ntfrcv/listen-on-ipv4-and-ipv6-interfaces.py). It seems to run well Since I use the pysnmp_app to send an trap information. But when I use the:

    p_model.apiTrapPDU.setVarBinds(trapsUDP, var)

to build a PDU and finish sending. the code shows like that:

    Var-binds:
    name = value
   name_ = value

(use SNMPv1) I try to read the source code. but it's difficult to me. also I'd like ask for help about this code:

    transportDispatcher.registerTransport(udp.domainName,  udp.UdpSocketTransport().openServerMode(('localhost',1)

I may guess the usage through the name. Any more, I still want get more information from the author.

Appreciate it.

**Comment by etingof** [comment]
Let's unwrap the call. This creates the object with a UDP socket prepared for network communication:

    udp.UdpSocketTransport()

Then this binds the socket to specific interface/port:

    udp.UdpSocketTransport().openServerMode(('localhost',1))

By this point I/O object is ready for communication. But we need to tie it up with SNMP core so that it could pass SNMP packets to the I/O object and vice-versa:

    registerTransport(udp.domainName,  udp.UdpSocketTransport().openServerMode(('localhost',1)

The `domainName` constant is an ID for this I/O object (UDP over IPv4) at the SNMP core. When you ask SNMP core to send SNMP message to another SNMP system across the network, you will use that `domainName` ID to direct SNMP core towards specific network transport to use. It is not directly relevant to the network address which you will also provide.

**Comment by EvoBloody** [comment]
Sorry for late. After 7 days reading your document and other examples. Here I'm sure How my code work. and also I know why varbind can't get the oid and var. Thank you.

**Comment by etingof** [comment]
That is the very good question!

There is currently no ready-to-use solution to this, although I am working on an automation for that and you can probably try to use the things we've got so far.

So there is the [mibdump](http://snmplabs.com/pysmi/mibdump.html) tool which can read up all the 10000 MIBs and build a single [huge index](mibs.snmplabs.com/json/index.json) mapping (among other things) the top-level MIB OID to MIB name. 

Given that index you can search it by the OID (e.g. by its prefix because your OID might be longer than the MIB's top-level OID) and come up with the MIB defining the OID.

**Comment by EvoBloody** [comment]
Yeah, The tool works well. but there is a problem, when I try to load module named "CTRON-DLSW-MIB" it turns out 

`"Smib Error: No symbol BRIDGE-MIB::MacAddress at xxxx"`

I found the problem is that "CTRON-DLSW-MIB" try to import symbol "MacAddress" from "BRIDGE-MIB", but "BRIDGE-MIB" import the same one from "SNMPv2-TC", After I rewrite "CTRON-DLSW-MIB.py" and make it import the Symbol from "SNMPv2-TC", it's no problem.

Also, this error appear in other MIBS like "RADLAN-rlFft"、"ChrComPmSonetSNT-P-Current-MIB" .etc

Is this a non-standard MIB? or something you may have not noticed.
