### ISSUE TITLE
Cannot install pysnmp on centos 6.9

### ISSUE THREAD

**Issue by kanchimo** [etingof/pysnmp#120]
Encounter following error:
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7dAqqZ/pycryptodomex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iwW9QE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-7dAqqZ/pycryptodomex/

Please help me to deal with it,

Thanks

**Comment by etingof** [comment]
This problem is related to the [pycryptodome](https://github.com/Legrandin/pycryptodome/issues) package, not pysnmp. But it is also quite possible that your build environment is incomplete (e.g. some *devel* .rpms are missing).

Alternatively, you may want to install `pycryptodomex` in its *wheel* form which should contain pre-compiled binaries.
