### ISSUE TITLE
Set variable value with setCmd

### ISSUE THREAD

**Issue by nadavishe** [etingof/pysnmp#132]
Hello,
 
I don’t success to set variables with setCmd

errorIndication, errorStatus, errorIndex, varBinds = next(
    setCmd(SnmpEngine(),
           CommunityData('private'),
           UdpTransportTarget(('10.208.255.73', 162)),
           ContextData(),
           ObjectType(ObjectIdentity('1.3.6.1.4.1.15921.20.23.1.1.1.15.1.1.1'),'abc'))
)

I receive:

pysnmp.smi.error.SmiError: MIB object ObjectIdentity('SNMPv2-SMI', 'enterprises', '15921.20.23.1.1.1') is not OBJECT-TYPE (MIB not loaded?)

Thanks

**Comment by etingof** [comment]
That happens because you pass it a Python value ("abc") to be set on the Agent. SNMP needs to know the SNMP type of that value to build proper message. There are two ways how pysnmp can discover SNMP type for the value:

* Look it up at the MIB
* Rely on you to supply SNMP type

Since you have not given it SNMP type, pysnmp tried to find it in a MIB but failed to find it.

To hint it on SNMP type just pass SNMP value object instead of pure Python value:

    ObjectType(ObjectIdentity('1.3.6.1.4.1.15921.20.23.1.1.1.15.1.1.1'), OctetString('abc')))

...assuming that this OID's type is OCTET STRING.
