### ISSUE TITLE
Trying to use nextCmd with asyncio, infinite loop over first element

### ISSUE THREAD

**Issue by Djailla** [etingof/pysnmp#160]
Here is the code I try to use. My goal is to use asyncio/pysnmp to poll Raritan PDU probes. As the number of probes is unknown, I need to walk over elements. No issues with synchronous method. But with async, I kept receiving the first item.

Any idea ?

    import logging
    import asyncio

    from pysnmp.entity.rfc3413.oneliner import cmdgen
    from pysnmp.hlapi.asyncio import (
        nextCmd,
        CommunityData,
        UdpTransportTarget,
        SnmpEngine,
        ContextData,
        ObjectIdentity,
        ObjectType,
    )
    from pysnmp.error import PySnmpError

    LOGGER = logging.getLogger(__name__)

    HOSTNAME = 'xxxxxxxxxxx'
    OIDS = [
        '1.3.6.1.4.1.13742.6.3.6.3.1.3',
        '1.3.6.1.4.1.13742.6.5.5.3.1.4.1',
        '1.3.6.1.4.1.13742.6.3.6.3.1.2.1',
    ]

    def snmp_requests(host, *oids):
        """Query SNMP oids."""
        cmd_gen = cmdgen.CommandGenerator()
        try:
            error_indication, error_status, error_index, varbind_table = (
                cmd_gen.nextCmd(
                    cmdgen.CommunityData('public'),
                    cmdgen.UdpTransportTarget((host, 161)),
                    *oids
                )
            )

        except PySnmpError as exc:
            logging.warning(exc)
            return None

        if error_indication:
            logging.warning('%s with this asset: %s', error_indication, host)

        elif error_status:
            logging.warning(
                '%s at %s',
                error_status.prettyPrint(),
                error_index and varbind_table[-1][int(error_index) - 1] or '?'
            )

        else:
            print(varbind_table)

    async def async_next_snmp_request(host, *oids):
        """Walk SNMP oids asynchronously."""
        oid_values = [ObjectType(ObjectIdentity(oid)) for oid in oids]
        while True:
            try:
                error_indication, error_status, error_index, varbind_table = (
                    await nextCmd(
                        SnmpEngine(),
                        CommunityData('public', mpModel=0),
                        UdpTransportTarget((host, 161)),
                        ContextData(),
                        *oid_values,
                    )
                )
            except PySnmpError:
                LOGGER.exception("PySNMP error")
                return

            if error_indication:
                LOGGER.warning('%s with this asset: %s', error_indication, host)
                return

            elif error_status:
                LOGGER.warning(
                    '%s at %s',
                    error_status.prettyPrint(),
                    error_index and varbind_table[-1][int(error_index) - 1] or '?'
                )
                return

            else:
                print(varbind_table)
                yield varbind_table

    async def async_snmp_walk(host, *oids):
        async for varbind in async_next_snmp_request(host, *oids):
            print(varbind)

    def test_async():
        loop = asyncio.get_event_loop()
        tasks = [
            loop.create_task(
                async_snmp_walk(HOSTNAME, *OIDS)
            )
        ]

        result = loop.run_until_complete(
            asyncio.wait(
                tasks,
                loop=loop,
            )
        )
        return result

    print('SYNC')
    snmp_requests(HOSTNAME, *OIDS)
    print('------------------------')
    print('ASYNC')
    test_async()

Output :

    SYNC
    [[ObjectType(ObjectIdentity(<ObjectName value object at 0x10392a358 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.1]>), <OctetString value object at 0x10392a438 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300505]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x10392a518 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.1]>), <Integer value object at 0x10392a5c0 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [234]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x10392a668 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.2.1.1]>), <Integer value object at 0x10392a748 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [10]>)], [ObjectType(ObjectIdentity(<ObjectName value object at 0x10392a630 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.2]>), <OctetString value object at 0x10392a1d0 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300505]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x10393b588 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.2]>), <Integer value object at 0x10393b5c0 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [36]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x10393b5f8 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.2.1.2]>), <Integer value object at 0x10393b710 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [11]>)], [ObjectType(ObjectIdentity(<ObjectName value object at 0x10392a6a0 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.3]>), <OctetString value object at 0x103aa5dd8 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300506]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x10393b470 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.3]>), <Integer value object at 0x10393b898 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [222]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x10393ba58 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.2.1.3]>), <Integer value object at 0x10393bb38 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [10]>)], [ObjectType(ObjectIdentity(<ObjectName value object at 0x103aa4978 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.4]>), <OctetString value object at 0x10393b4a8 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300506]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x10393bac8 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.4]>), <Integer value object at 0x10393bc88 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [41]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x10393be48 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.2.1.4]>), <Integer value object at 0x10393bf28 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [11]>)]]
    ------------------------
    ASYNC
    [[ObjectType(ObjectIdentity(<ObjectName value object at 0x103c98278 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.1]>), <OctetString value object at 0x103c49400 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300505]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x103c98400 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.1]>), <Integer32 value object at 0x103c98160 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [234]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x103c98518 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.2.1.1]>), <Integer32 value object at 0x103c985f8 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [10]>)]]
    [[ObjectType(ObjectIdentity(<ObjectName value object at 0x103c98278 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.1]>), <OctetString value object at 0x103c49400 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300505]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x103c98400 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.1]>), <Integer32 value object at 0x103c98160 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [234]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x103c98518 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.2.1.1]>), <Integer32 value object at 0x103c985f8 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [10]>)]]
    [[ObjectType(ObjectIdentity(<ObjectName value object at 0x103fa52e8 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.1]>), <OctetString value object at 0x103c9f2b0 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300505]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x103fa5470 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.1]>), <Integer32 value object at 0x103fa51d0 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [235]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x103fa5588 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.2.1.1]>), <Integer32 value object at 0x103fa5668 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [10]>)]]
    [[ObjectType(ObjectIdentity(<ObjectName value object at 0x103fa52e8 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.1]>), <OctetString value object at 0x103c9f2b0 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300505]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x103fa5470 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.1]>), <Integer32 value object at 0x103fa51d0 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [235]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x103fa5588 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.2.1.1]>), <Integer32 value object at 0x103fa5668 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [10]>)]]
    [[ObjectType(ObjectIdentity(<ObjectName value object at 0x1040f1080 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.1]>), <OctetString value object at 0x103f01f98 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300505]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x1040f1208 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.1]>), <Integer32 value object at 0x103f01ef0 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [235]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x1040f1320 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.2.1.1]>), <Integer32 value object at 0x1040f1400 tagSet <TagSet object at 0x102ec0c50 tags 0:0:2> subtypeSpec <ConstraintsIntersection object at 0x102e92e48 consts <ValueRangeConstraint object at 0x102e92e10 consts -2147483648, 2147483647>> payload [10]>)]]
    [[ObjectType(ObjectIdentity(<ObjectName value object at 0x1040f1080 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.3.6.3.1.3.1.1]>), <OctetString value object at 0x103f01f98 tagSet <TagSet object at 0x102f14a90 tags 0:0:4> subtypeSpec <ConstraintsIntersection object at 0x102f4d5f8 consts <ValueSizeConstraint object at 0x102f4d5c0 consts 0, 65535>> encoding iso-8859-1 payload [AEI7300505]>), ObjectType(ObjectIdentity(<ObjectName value object at 0x1040f1208 tagSet <TagSet object at 0x102f14ef0 tags 0:0:6> payload [1.3.6.1.4.1.1374....6.5.5.3.1.4.1.1]

**Comment by etingof** [comment]
Do you really need to loop over the `nextCmd` in the async version? As [explained here](http://snmplabs.com/pysnmp/docs/hlapi/asyncio/manager/cmdgen/nextcmd.html) the `nextCmd` call returns a generator object which asyncio main loop iterates over until it's exhausted.

As a side note: it's better to keep a single, reusable `SnmpEngine` object within your script/thread. This object is expensive to initialized, it holds various caches so re-creating it slows down pysnmp a great deal.

Also, if you'd use the [main stream pysnmp API](http://snmplabs.com/pysnmp/docs/hlapi/asyncore/sync/manager/cmdgen/nextcmd.html) for your synchronous version, it might look more concise and pretty  much lined up with the async version. 

Sorry for the nitpicking on your code! ;-)

**Comment by Djailla** [comment]
Do you really need to loop over the nextCmd in the async version? As explained here the nextCmd call returns a generator object which asyncio main loop iterates over until it's exhausted.

As a side note: it's better to keep a single, reusable SnmpEngine object within your script/thread. This object is expensive to initialized, it holds various caches so re-creating it slows down pysnmp a great deal.

Also, if you'd use the main stream pysnmp API for your synchronous version, it might look more concise and pretty much lined up with the async version.

Sorry for nitpicking on your code! ;-)

**Comment by Djailla** [comment]
@etingof 

> Do you really need to loop over the nextCmd in the async version? As explained here the nextCmd call returns a generator object which asyncio main loop iterates over until it's exhausted.

I would like to have a SNMP poller in async mode, either doing next or get commands. So yes, I want the next command to run in async to loop over entries in a table. I can see in the documentation that the `nextCmd` should return a generator, but I cannot make it work properly. Did you already test this in real ?

> As a side note: it's better to keep a single, reusable SnmpEngine object within your script/thread. This object is expensive to initialized, it holds various caches so re-creating it slows down pysnmp a great deal.

Agreed

> Also, if you'd use the main stream pysnmp API for your synchronous version, it might look more concise and pretty much lined up with the async version.

If async works ok, sync will disappear ;)

> Sorry for nitpicking on your code! ;-)

No problem

>

**Comment by Djailla** [comment]
@etingof Works way better except, the isEndOfMib check will happen after parsing the full MIB, not just the elements in the current table.

I will check how to deal with it.

**Comment by etingof** [comment]
> the isEndOfMib check will happen after parsing the full MIB, not just the elements in the current table

I am not totally sure I understand your concern here, but I have to admit that MIBs are always parsed as a whole.

This business of [figuring out the end-of-mib condition](https://github.com/etingof/pysnmp/blob/pysnmp-4.4.5/pysnmp/entity/rfc3413/cmdgen.py#L21)  seems not to explicitly require parsed MIB...

**Comment by HyungKwangChoi** [comment]
@etingof 
Hi Etingof

I've added a debugging.

from pysnmp import debug

debug.setLogger(debug.Debug('io', 'msgproc', 'secmod'))



Your final script, seems not working....i don't why it's not working in my labtop.
could you please check what the problem is?

2020-02-26 16:33:59,735 pysnmp: running pysnmp version 4.4.12
2020-02-26 16:33:59,735 pysnmp: debug category 'io' enabled
2020-02-26 16:33:59,735 pysnmp: debug category 'msgproc' enabled
2020-02-26 16:33:59,736 pysnmp: debug category 'secmod' enabled
2020-02-26 16:33:59,989 pysnmp: WARNING: the socket module on this platform misses option IP_PKTINFO. Assuming its value is 8.
2020-02-26 16:33:59,990 pysnmp: WARNING: the socket module on this platform misses option IP_TRANSPARENT. Assuming its value is 19.
2020-02-26 16:33:59,990 pysnmp: WARNING: the socket module on this platform misses option SOL_IPV6. Assuming its value is 41.
2020-02-26 16:33:59,991 pysnmp: WARNING: the socket module on this platform misses option IPV6_RECVPKTINFO. Assuming its value is 49.
2020-02-26 16:33:59,991 pysnmp: WARNING: the socket module on this platform misses option IPV6_TRANSPARENT. Assuming its value is 75.
2020-02-26 16:34:00,661 pysnmp: addV1System: added new table entry communityIndex "s-3797832878901792113" communityName "public" securityName "s-3797832878901792113" contextEngineId " O¸?¨H" contextName "b''" transportTag "b''"
2020-02-26 16:34:00,855 pysnmp: prepareOutgoingMessage: PDU request-id 5101526 replaced with unique ID 13674607
2020-02-26 16:34:00,856 pysnmp: prepareOutgoingMessage: using contextEngineId <SnmpEngineID value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 5, 32>>, encoding iso-8859-1, payload [0x80004fb8057fa88e48]> contextName b''
2020-02-26 16:34:00,857 pysnmp: _sec2com: built securityName to communityName map, version 4: {(<SnmpAdminString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 0, 255>, <ValueSizeConstraint object, consts 1, 32>>, encoding utf-8, payload [s-3797832878901792113]>, <SnmpEngineID value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 5, 32>>, encoding iso-8859-1, payload [0x80004fb8057fa88e48]>, <SnmpAdminString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 0, 255>, <ValueSizeConstraint object, consts 0, 32>>, encoding utf-8, payload []>): <OctetString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>>, encoding iso-8859-1, payload [public]>}
2020-02-26 16:34:00,859 pysnmp: generateRequestMsg: using community <OctetString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>>, encoding iso-8859-1, payload [public]> for securityModel <SnmpSecurityModel value object, tagSet <TagSet object, tags 0:0:2>, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts -2147483648, 2147483647>, <ValueRangeConstraint object, consts 0, 2147483647>, <ValueRangeConstraint object, consts 1, 2147483647>>, payload [1]>, securityName <SnmpAdminString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 0, 255>>, encoding utf-8, payload [s-3797832878901792113]>, contextEngineId <SnmpEngineID value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint
object, consts 5, 32>>, encoding iso-8859-1, payload [0x80004fb8057fa88e48]> contextName b''
2020-02-26 16:34:00,862 pysnmp: generateRequestMsg: Message:
 version=0
 community=public
 data=PDUs:
  get-next-request=GetNextRequestPDU:
   request-id=13674607
   error-status=noError
   error-index=0
   variable-bindings=VarBindList:
    VarBind:
     name=1.3.6.1
     value=ObjectSyntax:
      simple=SimpleSyntax:
       empty=


    VarBind:
     name=1.3.6.1.4.1.13742.6.5.5.3.1.4.1
     value=ObjectSyntax:
      simple=SimpleSyntax:
       empty=


    VarBind:
     name=1.3.6.1.4.1.13742.6.3.6.3.1.2.1
     value=ObjectSyntax:
      simple=SimpleSyntax:
       empty=






2020-02-26 16:34:00,865 pysnmp: sendMessage: queuing transportAddress ('104.236.166.95', 161) outgoingMessage
00000: 30 4C 02 01 00 04 06 70 75 62 6C 69 63 A1 3F 02
00016: 04 00 D0 A8 6F 02 01 00 02 01 00 30 31 30 07 06
00032: 03 2B 06 01 05 00 30 12 06 0E 2B 06 01 04 01 EB
00048: 2E 06 05 05 03 01 04 01 05 00 30 12 06 0E 2B 06
00064: 01 04 01 EB 2E 06 03 06 03 01 02 01 05 00
2020-02-26 16:34:02,368 pysnmp: StatusInformation: {'errorIndication': RequestTimedOut('No SNMP response received before timeout')}
2020-02-26 16:34:02,370 pysnmp: prepareOutgoingMessage: PDU request-id 5101526 replaced with unique ID 13674608
2020-02-26 16:34:02,370 pysnmp: prepareOutgoingMessage: using contextEngineId <SnmpEngineID value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 5, 32>>, encoding iso-8859-1, payload [0x80004fb8057fa88e48]> contextName b''
2020-02-26 16:34:02,371 pysnmp: generateRequestMsg: using community <OctetString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>>, encoding iso-8859-1, payload [public]> for securityModel <SnmpSecurityModel value object, tagSet <TagSet object, tags 0:0:2>, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts -2147483648, 2147483647>, <ValueRangeConstraint object, consts 0, 2147483647>, <ValueRangeConstraint object, consts 1, 2147483647>>, payload [1]>, securityName <SnmpAdminString value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint object, consts 0, 255>>, encoding utf-8, payload [s-3797832878901792113]>, contextEngineId <SnmpEngineID value object, tagSet <TagSet object, tags 0:0:4>, subtypeSpec <ConstraintsIntersection object, consts <ValueSizeConstraint object, consts 0, 65535>, <ValueSizeConstraint
object, consts 5, 32>>, encoding iso-8859-1, payload [0x80004fb8057fa88e48]> contextName b''
~
~ 
repeated

**Comment by etingof** [comment]
That's hard to say... Maybe try to enable full debugging to see if the message goes out to the wire? Or Wireshark it?

Given that on some other place it works, may be it's dependent on Python version?

**Comment by HyungKwangChoi** [comment]
Hi Ilya

Thanks for the replay.

Can I ask you a simple question?


  *   Questions

1. When you run your code, what’s your python version and pysnmp version?
          2. Could you please check it with diff or send me your test&debugging outputs  “Your scripts.py” so that I find with diff what the problem is.


  *   https://stackoverflow.com/questions/57301317/asyncio-code-in-pysnmp-is-not-responding-as-expected


  *   In your code attached “Your scripts.py”, I’ve only added&changed&deleted below.

from pysnmp import debug
debug.setLogger(debug.Debug('all'))

                                     snmp.UdpTransportTarget((host, 161), timeout=1, retries=0),

    tasks.append(get('demo.snmplabs.com','1.3.6.1.2.1.1.1.0'))


  *   My installation info

  *   Python 3.7.3
  *   Pysnmp(4.4.12)

PS C:\Python37\studyrootm\project\Tools for networks_V4.1(pysnmp)> python --version
Python 3.7.3

PS C:\Python37\studyrootm\project\Tools for networks_V4.1(pysnmp)> pip install pysnmp
Requirement already satisfied: pysnmp in c:\python37\lib\site-packages (4.4.12)
Requirement already satisfied: pyasn1>=0.2.3 in c:\python37\lib\site-packages (from pysnmp) (0.4.8)
Requirement already satisfied: pycryptodomex in c:\python37\lib\site-packages (from pysnmp) (3.9.7)
Requirement already satisfied: pysmi in c:\python37\lib\site-packages (from pysnmp) (0.3.4)
Requirement already satisfied: ply in c:\python37\lib\site-packages (from pysmi->pysnmp) (3.11)


  *   My problem is

Actually packet with asyncio feature is not going out. With Wireshark, I could see no packet sent.

But if I don’t use asyncio feature, I can use it as usual.  (“working script.py”)

/HyungKwang
