### ISSUE TITLE
pyasn1.error.PyAsn1Error: Duplicate name

### ISSUE THREAD

**Issue by faysal-ishtiaq** [etingof/pysnmp#275]
for the following block of code
```python
for (errorIndication,
     errorStatus,
     errorIndex,
     varBinds) in nextCmd(SnmpEngine(),
                          CommunityData('public'),
                          UdpTransportTarget(('192.168.0.222', 161)),
                          ContextData(),
                          ObjectType(
                              ObjectIdentity("SNMPv2-MIB", "sysObjectID").addAsn1MibSource('http://mibs.snmplabs.com/asn1/@mib@').loadMibs('ExaltComProducts')
                          ),
                          lexicographicMode=False):

    if errorIndication:
        print(errorIndication)
        break
    elif errorStatus:
        print('%s at %s' % (errorStatus.prettyPrint(),
                            errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
        break
    else:
        for varBind in varBinds:
            print(' = '.join([x.prettyPrint() for x in varBind]))
```

this error is produce:
`'pyasn1.error.PyAsn1Error: Duplicate name mQPSK\n']caused by <class 'pyasn1.error.PyAsn1Error'>: Duplicate name mQPSK`

**Comment by etingof** [comment]
Sounds like the `ExaltComm` MIB has an error - multiple `mQPSK` symbols here:

```
    AcmModulationT ::= TEXTUAL-CONVENTION
        STATUS current
        DESCRIPTION "These are the supported ACM Modulation types. When ACM is disabled or when telemetry is down, the modulation is -9999."
        SYNTAX INTEGER {
           notAvailable( -9999 ),
           mQPSK( 0 ),
           m8PSK( 7 ),
           m16QAM( 1 ),
           m32QAM( 5 ),
           m64QAM( 2 ),
           m128QAM( 3 ),
           m256QAM( 4 ),
           m512QAM( 6 ),
           mBPSK( 8 ),
           mQPSK( 9 ),
           m8PSK( 10 ),
           m32QAM( 11 ),
           m64QAM( 12 ),
           m128QAM( 13 ),
           m16QAM( 14 ),
           m512QAM( 15 ),
           mQPSK( 16 ),
           mBPSK( 17 )
        }
```

The latest (yet unreleased) [pysmi](https://github.com/etingof/pysmi) has a workaround engineered into to handle such situation. So you may want to either use the latest version in your application or just use it one-time to compile required MIBs into Python (with `mibdump` tool).

**Comment by faysal-ishtiaq** [comment]
Thanks a looooooooot :)

**Comment by mchingotto** [comment]
Hello,
   Sorry for bothering you, but I would need some help, please.
   I am dealing with this from a particular MIB:

    (look at the number 16748552)

    Add:  bnameE8000ESU91SPUC01(16748552),    --Eudemon8000E-X,SU91SPUC01,40G ......
    Add:  subbnameEudemon8000ECR52L1XX0(16748552),  --1-port 10GBase WAN/LAN XFP......
    
   The problem is some MIBs have duplicated numbers. I tried to compile them with mibdump.py and that's ok, but at the moment of loading them, the error raises an exception like this:

   File "/usr/local/lib/python3.9/site-packages/pyasn1/type/namedval.py", line 77, in __init__\n    raise error.PyAsn1Error(\'Duplicate number  %s=%s\' % (name, number))\n', 'pyasn1.error.PyAsn1Error: Duplicate number  bnameUSG9100SU61SPUA=16748552\n']caused by <class 'pyasn1.error.PyAsn1Error'>: Duplicate number  bnameUSG9100SU61SPUA=16748552

Could you please give me a clue?
Thank you, I really appreciate it.
M
