### ISSUE TITLE
writing pysnmp agent with tabular data and handler class

### ISSUE THREAD

**Issue by pcuzner** [etingof/pysnmp#304]
I've implemented a custom MIB (checks out fine with smilint) that maps MibScalars to a method in a MibHandler class within my agent. This works fine for scalars, but I need to extend the MibHandler to deal with tabular content. At this point, when I build the mib for the agent, I convert the  MibTableColumn to a Scalar but I don't know how to make the handler deal with multiple rows?

Is there some example code out there that shows how a handler class could be used to support a table? (I couldn't find any!)

Here's an example of the handler
```
class MyMibHandler(object):
    def __init__(self, name):
        self._lock = threading.RLock()
        self._name = name
        self._test_count = 0
        # I want to respond to a walk of the table with this content
        self.data = {
            1:"name1",
            2:"name2"
        }

    # Simple Scalars
    def testDescription(self):
        with self._lock:
            return " My scalars string"

    def errorMsg(self):
        with self._lock:
            return "error messsage test string"

    def testCount(self):
        with self._lock:
            return self._test_count

    # Table handling
    def tableKey(self):
        with self._lock:
            return "1"

    def tableName(self):
        with self._lock:
            return "myPool"
```
When the Mib is built I've just been overriding readGet
```
def createVariable(SuperClass, getValue, *args):
    class Var(SuperClass):
        def readGet(self, name, *args):
            return name, self.syntax.clone(getValue())
    return Var(*args)
```

**Comment by etingof** [comment]
> I don't know how to make the handler deal with multiple rows?

I am not quite sure I understand what exactly is the problem here. For pure GET/GETNEXT there seems to be no difference between scalars and tables - both are just ordered OIDs.

The difference comes up with SET operation. For scalars you can just change their value, however with tables you can create/delete the entire rows or even multiple rows in dependent tables by operating on a single column.

Also, with tables, row consistency can be enforced by requiring certain columns to be present.

**Comment by pcuzner** [comment]
OK thanks.
