### ISSUE TITLE
SmiError: Excessive instance identifier sub-OIDs left at MibTableRow

### ISSUE THREAD

**Issue by jframeau** [etingof/pysnmp#6]
Hi,

I'm trying to extract some values from a Ruckus ZoneDirector (https://raw.githubusercontent.com/librenms/librenms/master/mibs/RUCKUS-ZD-WLAN-MIB), specifically ruckusZDWLANAPStatus field.

ruckusZDWLANAPStatus field is from table ruckusZDWLANAPTable (.1.3.6.1.4.1.25053.1.2.2.1.1.2.1)

Output from snmpwalk is:

SNMPv2-SMI::enterprises.25053.1.2.2.1.1.2.1.1.1.6.44.197.211.51.83.176 = Hex-STRING: 2C C5 D3 33 53 B0
SNMPv2-SMI::enterprises.25053.1.2.2.1.1.2.1.1.1.6.44.197.211.51.87.0 = Hex-STRING: 2C C5 D3 33 57 00
SNMPv2-SMI::enterprises.25053.1.2.2.1.1.2.1.1.1.6.44.197.211.51.90.144 = Hex-STRING: 2C C5 D3 33 5A 90
SNMPv2-SMI::enterprises.25053.1.2.2.1.1.2.1.1.1.6.44.197.211.51.90.192 = Hex-STRING: 2C C5 D3 33 5A C0
SNMPv2-SMI::enterprises.25053.1.2.2.1.1.2.1.1.1.6.44.197.211.51.104.112 = Hex-STRING: 2C C5 D3 33 68 70
SNMPv2-SMI::enterprises.25053.1.2.2.1.1.2.1.1.1.6.44.197.211.51.104.144 = Hex-STRING: 2C C5 D3 33 68 90

I wonder if pysnmp handles these kinds of sequence where index is not a simple number.

Pysnmp 4.3.2.

jfr

**Comment by etingof** [comment]
Yes, pysnmp fully supports all kinds of SNMP indices. The problem with your example is that the last sub-OID does not fit the index:

    $ snmptranslate.py  RUCKUS-ZD-WLAN-MIB::1.3.6.1.4.1..25053.1.2.2.1.1.2.1.1.1.6.44.197.211.51.83
    RUCKUS-ZD-WLAN-MIB::ruckusZDWLANAPMacAddr."06:2c:c5:d3:33:53"
   $ snmptranslate.py  RUCKUS-ZD-WLAN-MIB::1.3.6.1.4.1..25053.1.2.2.1.1.2.1.1.1.6.44.197.211.51.83.176
   pysnmp.smi.error.SmiError: Excessive instance identifier sub-OIDs left at MibTableRow((1, 3, 6, 1, 4, 1, 25053, 1, 2, 2, 1, 1, 2, 1, 1), None): (176,)

Sometimes that happens when agent and manager implement different versions of the same MIB. Could you check if other versions of RUCKUS-ZD-WLAN exist?

You could work around this problem by disabling MIB resolution (lookupMib = False) at pysnmp hlapi. Or make a local copy of RUCKUS-ZD-WLAN adding another (fake) index to that table...

**Comment by cissuppandi** [comment]
Hi etingof,
Good Day.
I have tried to load a custom mib and did a snmp walk. but I am getting the below mentioned error.I have parse the mib file through the mibdump.py and format as pysnmp. I have tried the above solution mentioned by you but unfortunately it didn't help. I will be highly obliged if you can provide some more solution for the above issue.
***********************ERROR*****************************
AMIT-PDU-MIB::pduNamePlateTableSize.0 = 2
AMIT-PDU-MIB::pduNamePlateIndex.1 = 1
AMIT-PDU-MIB::pduNamePlateIndex.2 = 2
AMIT-PDU-MIB::pduNamePlateName.1 = 
AMIT-PDU-MIB::pduNamePlateName.2 = 
AMIT-PDU-MIB::pduNamePlateLocation.1 = 
AMIT-PDU-MIB::pduNamePlateLocation.2 = 
Traceback (most recent call last):
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
  File "G:\Python\lib\asyncore.py", line 207, in loop
    poll_fun(timeout, map)
  File "G:\Python\lib\asyncore.py", line 150, in poll
    read(obj)
  File "G:\Python\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "G:\Python\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "G:\Python\lib\asyncore.py", line 422, in handle_read_event
    self.handle_read()
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dgram\base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\base.py", line 70, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\proto\rfc3412.py", line 486, in receiveMessage
    cachedParams['cbCtx'])
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\rfc3413\cmdgen.py", line 152, in processResponsePdu
    cbFun(snmpEngine, origSendRequestHandle, None, PDU, cbCtx)
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\rfc3413\cmdgen.py", line 303, in processResponseVarBinds
    varBindTable, cbCtx):
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\cmdgen.py", line 345, in __cbFun
    varBindTable],
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\cmdgen.py", line 344, in <listcomp>
    [vbProcessor.unmakeVarBinds(snmpEngine, varBindTableRow, lookupMib) for varBindTableRow in
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\varbinds.py", line 46, in unmakeVarBinds
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\varbinds.py", line 46, in <listcomp>
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\rfc1902.py", line 847, in resolveWithMib
    self.__args[0].resolveWithMib(mibViewController)
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\rfc1902.py", line 450, in resolveWithMib
    self.__indices = rowNode.getIndicesFromInstId(suffix)
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\mibs\SNMPv2-SMI.py", line 1258, in getIndicesFromInstId
    (self, instId)
pysnmp.smi.error.SmiError: Excessive instance identifier sub-OIDs left at MibTableRow((1, 3, 6, 1, 4, 1, 1111, 1, 1, 2, 1), None): 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/CIS-Guest/PycharmProjects/AMIT_Automation/SNMP_V1/test_walk.py", line 24, in <module>
    ObjectType(ObjectIdentity('AMIT-PDU-MIB', 'pdu')),lookupMib=True,ignoreNonIncreasingOid=True
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\sync\cmdgen.py", line 362, in nextCmd
    snmpEngine.transportDispatcher.runDispatcher()
  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dispatch.py", line 50, in runDispatcher
    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "G:\Python\lib\asyncore.py", line 207, in loop
    poll_fun(timeout, map)
;  File "G:\Python\lib\asyncore.py", line 150, in poll
    read(obj)
;  File "G:\Python\lib\asyncore.py", line 87, in read
    obj.handle_error()
;  File "G:\Python\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
;  File "G:\Python\lib\asyncore.py", line 422, in handle_read_event
    self.handle_read()
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\asyncore\dgram\base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\carrier\base.py", line 70, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\proto\rfc3412.py", line 486, in receiveMessage
    cachedParams['cbCtx'])
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\rfc3413\cmdgen.py", line 152, in processResponsePdu
    cbFun(snmpEngine, origSendRequestHandle, None, PDU, cbCtx)
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\entity\rfc3413\cmdgen.py", line 303, in processResponseVarBinds
    varBindTable, cbCtx):
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\cmdgen.py", line 345, in __cbFun
    varBindTable],
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\asyncore\cmdgen.py", line 344, in <listcomp>
    [vbProcessor.unmakeVarBinds(snmpEngine, varBindTableRow, lookupMib) for varBindTableRow in
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\varbinds.py", line 46, in unmakeVarBinds
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\hlapi\varbinds.py", line 46, in <listcomp>
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\rfc1902.py", line 847, in resolveWithMib
    self.__args[0].resolveWithMib(mibViewController)
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\rfc1902.py", line 450, in resolveWithMib
    self.__indices = rowNode.getIndicesFromInstId(suffix)
;  File "C:\Users\CIS-Guest\PycharmProjects\AMIT_Automation\venv\lib\site-packages\pysnmp\smi\mibs\SNMPv2-SMI.py", line 1258, in getIndicesFromInstId
    (self, instId)
;pysnmp.smi.error.SmiError: Excessive instance identifier sub-OIDs left at MibTableRow((1, 3, 6, 1, 4, 1, 1111, 1, 1, 2, 1), None): 1
caused by <class 'pysnmp.smi.error.SmiError'>: Excessive instance identifier sub-OIDs left at MibTableRow((1, 3, 6, 1, 4, 1, 1111, 1, 1, 2, 1), None): 1

**Comment by etingof** [comment]
Can you please share that `AMIT-PDU-MIB` as well as its non-standard dependencies?

**Comment by cissuppandi** [comment]
Hi etingof,

Thanks for the reply.I have send the mib for your reference.All the dependency also mentioned in the MIB itself.Please let me know if you need more details for anything.

**Comment by cissuppandi** [comment]
Hi etingof,

Any updates for the above.Please provide you comment for the same. I have faced another issue while I am try to run snmp v3 via pysnmp . I am getting the the following error.

{'sendPduHandle': 9678068}

Attached the log file for your reference.
Your help is much appreciated

[log.txt](https://github.com/etingof/pysnmp/files/3301243/log.txt)

Thanks 
Amit
