### ISSUE TITLE
CVE-2013-7459 :-critical. eap-based buffer overflow in the ALGnew function in block_templace.c in Python Cryptography Toolkit (aka pycrypto

### ISSUE THREAD

**Issue by lokeshjain279** [etingof/pysnmp#99]
We are using pysnmp version 4.3.2 which has pycrypto 2.6.1 as it’s dependency. We have recently identified an open security issue against pycrypto which is  CVE-2013-7459
CVSS score (version 3.0) 9.8. It is ranked as critical. eap-based buffer overflow in the ALGnew function in block_templace.c in Python Cryptography Toolkit (aka pycrypto) allows remote attackers to execute arbitrary code as demonstrated by a crafted iv parameter to cryptmsg.py.

I know that pycrypto is no more maintained and that’s the reason why pysnmp has replaced pycrypto with pycrptodome in newer releases. I just want to confirm if this vulnerability affects pysnmp 4.3.2 in anyway? Please note that we don’t use pycrypto directly but only as a dependency of pysnmp. If this issue affects pysnmp , was there a patched version of pysnmp 4.3.2 which has this issue addressed?

**Comment by etingof** [comment]
Thank you for rising this!

I can't tell you for sure that you are safe because I am not an expert in PyCrypto code base.

What I can tell you is how pysnmp 4.3.2 uses PyCrypto. These are all the PyCrypto call occurrences I've been able to find:

* [DES](https://github.com/etingof/pysnmp/blob/87a7a35d1e9f762210c7520315158ceb5f5487d9/pysnmp/proto/secmod/rfc3414/priv/des.py#L16)
* [DES3](https://github.com/etingof/pysnmp/blob/87a7a35d1e9f762210c7520315158ceb5f5487d9/pysnmp/proto/secmod/eso/priv/des3.py#L24)
* [AES](https://github.com/etingof/pysnmp/blob/87a7a35d1e9f762210c7520315158ceb5f5487d9/pysnmp/proto/secmod/rfc3826/priv/aes.py#L15)

Let me know if I can help you any further with this.
